### ISSUE TITLE
User Story

### ISSUE THREAD

**Issue by AndrewMorrow** [AndrewMorrow/Project-2-Group-4#4]
This will be the reason behind the creation for the website and what problems we are trying to solve.

**Comment by jackparisi** [comment]
As a user I will use this site as a comprehensive gaming log, for past, present and future games in my collection.
The user is able to log in and be presented with the option of choosing to browse for a new game or log their past games.
The user is able to log past games played or currently in progress. The site will be able to recognize the game's genre and possible platforms. 
The user is able to search for new games by genre and platform. 
The user is presented with price options for the new games, and if they choose to add that to their backlog library.
